const c=document.getElementById('game'),ctx=c.getContext('2d');let W,H,dpr,img=new Image(),loaded=false;img.src='assets/master-map.png';img.onload=()=>{loaded=true};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
let me={x:.50,y:.58,dir:0},remote=new Map(),keys={},day=12;addEventListener('keydown',e=>keys[e.key.toLowerCase()]=1);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
const joy={x:0,y:0,active:false};const base=document.getElementById('joy'),stick=document.getElementById('stick');
function joyMove(e){const r=base.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=e.clientX-cx,dy=e.clientY-cy;const m=Math.hypot(dx,dy),lim=48;if(m>lim){dx=dx/m*lim;dy=dy/m*lim}joy.x=dx/lim;joy.y=dy/lim;stick.style.transform=`translate(${dx}px,${dy}px)`}
['pointerdown','pointermove'].forEach(ev=>base.addEventListener(ev,e=>{joy.active=true;base.setPointerCapture?.(e.pointerId);joyMove(e)}));['pointerup','pointercancel','pointerleave'].forEach(ev=>base.addEventListener(ev,()=>{joy.active=false;joy.x=joy.y=0;stick.style.transform='translate(0,0)'}));
let ws;try{const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(proto+'://'+location.host);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='welcome'){me.id=m.id;m.players.forEach(p=>p.id!==me.id&&remote.set(p.id,p));updateCount(m.players.length)}if(m.type==='join'){remote.set(m.player.id,m.player);updateCount(remote.size+1)}if(m.type==='state'&&m.player.id!==me.id)remote.set(m.player.id,m.player);if(m.type==='leave'){remote.delete(m.id);updateCount(remote.size+1)}if(m.type==='players'){remote.clear();m.players.forEach(p=>p.id!==me.id&&remote.set(p.id,p));updateCount(m.players.length)}}}catch{}
function updateCount(n){document.getElementById('players').textContent=n+'/20'}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),1600)}
document.getElementById('action').onclick=()=>toast('Poovattoor location interaction')
function draw(){requestAnimationFrame(draw);const speed=.00045;let ax=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+joy.x,ay=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+joy.y;const mag=Math.hypot(ax,ay);if(mag){ax/=Math.max(1,mag);ay/=Math.max(1,mag);me.x=Math.max(.015,Math.min(.985,me.x+ax*speed));me.y=Math.max(.015,Math.min(.985,me.y+ay*speed));me.dir=Math.atan2(ay,ax);if(ws?.readyState===1)ws.send(JSON.stringify({type:'state',x:me.x,y:me.y,dir:me.dir}))}
 day=(day+0.003)%24;document.getElementById('clock').textContent=String(Math.floor(day)).padStart(2,'0')+':'+String(Math.floor(day%1*60)).padStart(2,'0');
 ctx.clearRect(0,0,W,H);if(!loaded){ctx.fillStyle='#182018';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.fillText('Loading Poovattoor…',20,40);return}
 const scale=Math.max(W/img.width,H/img.height)*1.35;const mw=img.width*scale,mh=img.height*scale;const camX=me.x*mw,camY=me.y*mh;ctx.drawImage(img,W/2-camX,H/2-camY,mw,mh);
 const shade=Math.max(0,Math.abs(12-day)/12)*.48;ctx.fillStyle=`rgba(8,16,35,${shade})`;ctx.fillRect(0,0,W,H);
 for(const p of remote.values())drawPlayer(p.x*mw+W/2-camX,p.y*mh+H/2-camY,p.dir,false,p.name);drawPlayer(W/2,H/2,me.dir,true,'YOU');
 document.getElementById('place').textContent='Poovattoor · '+(me.x<.5?'Temple side':'Main road');}
function drawPlayer(x,y,dir,self,name){ctx.save();ctx.translate(x,y);ctx.rotate(dir);ctx.fillStyle=self?'#fff':'#ffd';ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#222';ctx.fillRect(3,-3,8,6);ctx.fillStyle='#000b';ctx.font='10px Arial';ctx.textAlign='center';ctx.fillText(name,0,-15);ctx.restore()}draw();
